### PR TITLE
lmplements the inter-process readers writer lock

### PR DESCRIPTION
**Pull request by psarka**
This PR implements an inter-process readers writer lock, as suggested in https://github.com/harlowja/fasteners/issues/42.

I tried to stay very close to the existing code, in particular the structure, naming conventions, supported versions and the API. I took a bit more liberties with refreshing the documentation and README file, as well as fixed travis and added a gitignore.

I'm a bit unhappy that the intersection of windows and unix lock features is very small, but I don't know what to do about that apart from trying to build a readers writer locks myself, from lower level primitives. I'm not sure it is easy to do that.

Let me know what you think!

### CODE REVIEW

**Comment by psarka** [comment]
@harlowja I'm waiting for this PR for my personal project, so I thought, maybe you need a hand with maintaining fasteners in general? I see many issues and PRs waiting, I could help out. Feel free to drop me an email at paulius.sarka@gmail.com.

**Comment by harlowja** [comment]
Ya, ownership is more than welcome :)

**Comment by psarka** [comment]
Cool! How can I get started?

**Comment by harlowja** [comment]
Hmmm, guess we need some kind of CODEOWNERS file with u in it?

**Comment by psarka** [comment]
As I understand from the docs, CODEOWNERS is optional. I think inviting me as a collaborator shoud be enough: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository

**Comment by harlowja** [comment]
Ah, ok, that works to.

**Comment by harlowja** [comment]
U've been invited.

**Comment by harlowja** [comment]
Resolve conflicts?

**Comment by psarka** [comment]
Done :+1:

**Review by harlowja — APPROVED** [review]

**Comment by harlowja** [comment]
Nice, I'm not sure if its possible to have travis update pypi, might be nice to do that; because it was just done by me before, lol

**Pull request merged**
