### PR TITLE
Bring back support for eventlets

### PR DESCRIPTION
**Pull request by psarka**

### CODE REVIEW

**Comment by psarka** [comment]
Supersedes https://github.com/harlowja/fasteners/pull/97
Closes: #96

**Comment by SeanMooney** [comment]
yep this is a more complete PR as it add a regression test for the eventlet case.

**Comment by psarka** [comment]
@SeanMooney Sorry for not merging your PR, I wanted to add a regression test for eventlet, but did not know how it should look like and how to ask you for modifications. By the time I figured it out, I already had the code...

In any case, thanks for figuring this one out, I'm glad the eventlet saga is finally over :crossed_fingers: I published 0.18 today, please integrate it into oslo whenever you have time.

Thanks again for you contribution! :pray:

**Comment by SeanMooney** [comment]
no worries at all
ill update https://review.opendev.org/c/openstack/oslo.concurrency/+/856120 and update it for 0.18

**Pull request merged**
